const STYLE_ID='twilight-ultimate-style';
const PANEL_ID='twilight-terror-panel';
const BUTTON_ID='twilight-terror-settings';
const FALLBACK_ID='twilight-terror-fallback';
const BG_ID='twilight-custom-background';
const defaults={accent:'#00e5ff',glow:55,background:'',avatar:'',callSound:'',messageSound:'',look:'neon',compact:false,blur:true,discordEffects:true};
const getSettings=()=>chrome.storage.local.get(defaults);
function esc(v){return String(v||'').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\)/g,'\\)')}
function applySettings(s){
 document.getElementById(STYLE_ID)?.remove();document.getElementById(BG_ID)?.remove();
 if(s.discordEffects===false)return;
 const style=document.createElement('style');style.id=STYLE_ID;const a=s.accent||'#00e5ff';const g=Math.max(0,Math.min(100,Number(s.glow??55)))/100;
 style.textContent=`:root{--terror-accent:${a}}#${BUTTON_ID},#${FALLBACK_ID}{display:flex!important;align-items:center!important;width:calc(100% - 12px)!important;box-sizing:border-box!important;margin:6px!important;padding:9px 12px!important;border:1px solid ${a}88!important;border-radius:8px!important;background:linear-gradient(135deg,${a}25,#09131b)!important;color:${a}!important;font-weight:800!important;cursor:pointer!important;z-index:2147483640!important}#${FALLBACK_ID}{position:fixed!important;left:18px!important;bottom:18px!important;width:auto!important;box-shadow:0 0 ${Math.round(22*g)}px ${a}55!important}#${PANEL_ID}{position:fixed!important;inset:0!important;z-index:2147483647!important;display:flex!important;align-items:center!important;justify-content:center!important;background:rgba(0,0,0,.72)!important;backdrop-filter:blur(8px)!important;font-family:Arial,sans-serif!important}#${PANEL_ID} .terror-card{width:min(820px,92vw);max-height:90vh;overflow:auto;background:#071018;border:1px solid ${a}66;border-radius:20px;box-shadow:0 0 55px ${a}33;color:#edfaff;padding:24px}#${PANEL_ID} h1{margin:0;color:${a};letter-spacing:2px;font-size:25px}.terror-sub{color:#8ca4ad;font-size:12px;margin:6px 0 18px}#${PANEL_ID} .terror-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:700px){#${PANEL_ID} .terror-grid{grid-template-columns:1fr}}#${PANEL_ID} .terror-box{background:#0b1720;border:1px solid #ffffff12;border-radius:12px;padding:14px}#${PANEL_ID} label{display:block;font-weight:800;margin-bottom:8px;color:#c7e1e8}#${PANEL_ID} input,#${PANEL_ID} select{width:100%;box-sizing:border-box;background:#050c12;color:#fff;border:1px solid ${a}44;border-radius:8px;padding:9px}#${PANEL_ID} input[type=color]{height:42px;padding:3px}#${PANEL_ID} button{border:0;border-radius:9px;padding:10px 14px;cursor:pointer}.terror-primary{background:${a};color:#001014;font-weight:900}.terror-secondary{background:#17252f;color:#d8eef3}.terror-actions{display:flex;gap:8px;margin-top:16px;flex-wrap:wrap}`;
 document.documentElement.appendChild(style);
 if(s.background){const bg=document.createElement('div');bg.id=BG_ID;bg.style.cssText=`position:fixed;inset:0;z-index:0;pointer-events:none;background-image:url("${esc(s.background)}");background-size:cover;background-position:center;background-repeat:no-repeat;filter:blur(${s.blur===false?'0':'8'}px);transform:scale(1.04);opacity:.42`;document.body.prepend(bg)}
}
function pick(accept,cb){const i=document.createElement('input');i.type='file';i.accept=accept;i.onchange=()=>{const f=i.files?.[0];if(!f)return;if(f.size>12*1024*1024){alert('Datei zu groß. Maximal 12 MB.');return}const r=new FileReader();r.onload=()=>cb(r.result,f.name);r.readAsDataURL(f)};i.click()}
function openPanel(){if(document.getElementById(PANEL_ID))return;getSettings().then(s=>{const w=document.createElement('div');w.id=PANEL_ID;w.innerHTML=`<div class="terror-card"><h1>⚡ TERROR SETTINGS</h1><div class="terror-sub">TWILIGHT-Einstellungen · lokal gespeichert</div><div class="terror-grid"><div class="terror-box"><label>🌌 Hintergrundbild</label><button class="terror-secondary" id="terror-bg">Bild auswählen</button><div id="terror-bg-name" class="terror-sub">${s.background?'Gespeichert':'Kein Bild'}</div></div><div class="terror-box"><label>👤 Profilbild-Darstellung</label><button class="terror-secondary" id="terror-avatar">Bild auswählen</button><div id="terror-avatar-name" class="terror-sub">${s.avatar?'Gespeichert':'Kein Bild'}</div></div><div class="terror-box"><label>📞 Anruf-Sound</label><button class="terror-secondary" id="terror-call">Sound auswählen</button> <button class="terror-secondary" id="terror-call-test">▶ Test</button></div><div class="terror-box"><label>🔔 Nachrichtensound</label><button class="terror-secondary" id="terror-msg">Sound auswählen</button> <button class="terror-secondary" id="terror-msg-test">▶ Test</button></div><div class="terror-box"><label>🎨 Akzentfarbe</label><input id="terror-accent" type="color" value="${s.accent}"></div><div class="terror-box"><label>✨ Glow</label><input id="terror-glow" type="range" min="0" max="100" value="${s.glow}"></div><div class="terror-box"><label>🪟 Theme</label><select id="terror-look"><option value="neon">TWILIGHT Neon</option><option value="midnight">Midnight</option><option value="glass">Glass</option><option value="minimal">Minimal Clean</option></select><label><input id="terror-blur" type="checkbox" ${s.blur!==false?'checked':''}> Hintergrund weichzeichnen</label></div><div class="terror-box"><label>⚙ Optionen</label><label><input id="terror-compact" type="checkbox" ${s.compact?'checked':''}> Compact Mode</label><label><input id="terror-effects" type="checkbox" ${s.discordEffects!==false?'checked':''}> TERROR Design aktiv</label></div></div><div class="terror-actions"><button class="terror-primary" id="terror-save">✓ ALLES SPEICHERN</button><button class="terror-secondary" id="terror-close">Schließen</button></div><div id="terror-status" class="terror-sub"></div></div>`;document.body.appendChild(w);document.getElementById('terror-look').value=s.look||'neon';
 const save=(k,v)=>chrome.storage.local.set({[k]:v});
 document.getElementById('terror-bg').onclick=()=>pick('image/*',(d,n)=>{s.background=d;save('background',d);document.getElementById('terror-bg-name').textContent=n;applySettings(s)});
 document.getElementById('terror-avatar').onclick=()=>pick('image/*',(d,n)=>{s.avatar=d;save('avatar',d);document.getElementById('terror-avatar-name').textContent=n});
 document.getElementById('terror-call').onclick=()=>pick('audio/*',(d,n)=>{s.callSound=d;save('callSound',d)});document.getElementById('terror-msg').onclick=()=>pick('audio/*',(d,n)=>{s.messageSound=d;save('messageSound',d)});
 document.getElementById('terror-call-test').onclick=()=>s.callSound&&new Audio(s.callSound).play().catch(()=>{});document.getElementById('terror-msg-test').onclick=()=>s.messageSound&&new Audio(s.messageSound).play().catch(()=>{});
 document.getElementById('terror-save').onclick=async()=>{s.accent=document.getElementById('terror-accent').value;s.glow=Number(document.getElementById('terror-glow').value);s.look=document.getElementById('terror-look').value;s.blur=document.getElementById('terror-blur').checked;s.compact=document.getElementById('terror-compact').checked;s.discordEffects=document.getElementById('terror-effects').checked;await chrome.storage.local.set(s);applySettings(s);document.getElementById('terror-status').textContent='✓ ALLES GESPEICHERT'};
 document.getElementById('terror-close').onclick=()=>w.remove();w.addEventListener('click',e=>{if(e.target===w)w.remove()})})}
function onSettings(){return /\/settings(?:\/|$)/i.test(location.pathname)}
function injectSettingsButton(){if(!onSettings()||document.getElementById(BUTTON_ID))return;const els=[...document.querySelectorAll('button,[role="button"],div')];const target=els.find(e=>{const a=(e.getAttribute('aria-label')||'').toLowerCase();const t=(e.textContent||'').trim().toLowerCase();return a.includes('user settings')||a.includes('benutzereinstellungen')||t==='user settings'||t==='benutzereinstellungen'});const b=document.createElement('button');b.id=BUTTON_ID;b.type='button';b.textContent='⚡ TERROR Settings';b.onclick=openPanel;if(target?.parentElement)target.parentElement.insertBefore(b,target.nextSibling);else{b.id=FALLBACK_ID;document.body.appendChild(b)}}
function discover(){const channels=[];const seen=new Set();document.querySelectorAll('a[href*="/channels/"]').forEach(a=>{const href=a.href||'';const name=(a.textContent||a.getAttribute('aria-label')||'').trim().replace(/\s+/g,' ');if(!href||!name||seen.has(href))return;seen.add(href);const parts=new URL(href).pathname.split('/').filter(Boolean);channels.push({name,server:parts[1]||'Discord',href})});return channels.slice(0,300)}
getSettings().then(applySettings);const observer=new MutationObserver(injectSettingsButton);observer.observe(document.documentElement,{childList:true,subtree:true});setInterval(injectSettingsButton,1500);
chrome.runtime.onMessage.addListener((msg,sendResponse)=>{if(msg?.type==='applySettings')getSettings().then(applySettings);if(msg?.type==='openTerrorSettings'){openPanel();sendResponse({ok:true});return true}if(msg?.type==='discover'){sendResponse({channels:discover()});return true}});