const DEFAULTS={accent:'#00e5ff',glow:55,background:'',avatar:'',callSound:'',messageSound:'',look:'neon',compact:false,blur:true,discordEffects:true};
const $=id=>document.getElementById(id);
let state={...DEFAULTS};
async function load(){state={...DEFAULTS,...await chrome.storage.local.get(DEFAULTS)};$('accent').value=state.accent;$('glow').value=state.glow;$('look').value=state.look;$('blur').checked=state.blur;$('compact').checked=state.compact;$('discordEffects').checked=state.discordEffects;$('backgroundState').textContent=state.background?'✓ Hintergrund gespeichert':'Kein Hintergrund gespeichert';$('avatarState').textContent=state.avatar?'✓ Profilbild gespeichert':'Kein Profilbild gespeichert';$('callState').textContent=state.callSound?'✓ Anruf-Sound gespeichert':'Standard';$('messageState').textContent=state.messageSound?'✓ Notification-Sound gespeichert':'Standard'}
function file(id,key,label){$(id).onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024){alert('Maximal 8 MB pro Datei.');e.target.value='';return}const r=new FileReader();r.onload=async()=>{state[key]=r.result;await chrome.storage.local.set({[key]:r.result});$(label).textContent='✓ '+f.name+' gespeichert';};r.readAsDataURL(f)}}
file('background','background','backgroundState');file('avatar','avatar','avatarState');file('callSound','callSound','callState');file('messageSound','messageSound','messageState');
$('testCall').onclick=async()=>{const r=await chrome.storage.local.get('callSound');if(r.callSound)new Audio(r.callSound).play().catch(()=>{})};$('testMessage').onclick=async()=>{const r=await chrome.storage.local.get('messageSound');if(r.messageSound)new Audio(r.messageSound).play().catch(()=>{})};
$('save').onclick=async()=>{state.accent=$('accent').value;state.glow=Number($('glow').value);state.look=$('look').value;state.blur=$('blur').checked;state.compact=$('compact').checked;state.discordEffects=$('discordEffects').checked;await chrome.storage.local.set(state);$('status').textContent='✓ ALLES GESPEICHERT';try{const tabs=await chrome.tabs.query({url:['https://discord.com/*','https://discordapp.com/*']});for(const t of tabs)if(t.id)chrome.tabs.sendMessage(t.id,{type:'applySettings'})}catch(e){}};
$('refreshChats').onclick=async()=>{const tabs=await chrome.tabs.query({url:['https://discord.com/*','https://discordapp.com/*']});if(!tabs.length){$('chatState').textContent='Discord ist nicht geöffnet.';return}try{const r=await chrome.tabs.sendMessage(tabs[0].id,{type:'discover'});const c=r?.channels||[];$('chatState').textContent=`✓ ${c.length} sichtbare Chats erkannt`;$('chatList').innerHTML=c.map(x=>`<div>▣ ${String(x.name).replace(/[<>&]/g,'')} <small>• ${String(x.server||'Discord').replace(/[<>&]/g,'')}</small></div>`).join('')||'Keine sichtbaren Channels gefunden.'}catch(e){$('chatState').textContent='Discord-Seite neu laden und erneut versuchen.'}};
$('export').onclick=async()=>{const r=await chrome.storage.local.get(DEFAULTS);const blob=new Blob([JSON.stringify(r)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='terror-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('import').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());const clean={};for(const k of Object.keys(DEFAULTS))if(k in data)clean[k]=data[k];await chrome.storage.local.set(clean);await load();$('status').textContent='✓ IMPORT GESPEICHERT'}catch(_){$('status').textContent='Import fehlgeschlagen.'}};$('reset').onclick=async()=>{if(!confirm('Wirklich alle TERROR Settings löschen?'))return;await chrome.storage.local.clear();await load();$('status').textContent='✓ ZURÜCKGESETZT'};
load();